spring:
  profiles:
    active: local
logging:
  config: classpath:logback-local.xml
datasource:
  traffic-monitor:
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://127.0.0.1/sample"
    username: postgres
    password: postgres
    initial-size: 2
    max-active: 4
    max-idle: 4
    min-idle: 2
    max-wait: 300
